name: stop EC2 Instance

on:
  workflow_dispatch:

jobs:
  start-ec2:
    runs-on: self1 

    steps:
      - name: Start EC2 instance
        run: aws ec2 stop-instances --instance-ids i-05d64044e9bbd7ea8
